### ISSUE TITLE
The output of all_genes.fna is empty.

### ISSUE THREAD

**Issue by gaojingxun** [metagentools/ConDiGA#2]
2024-11-16 04:29:55,788 - INFO - 59 were idenitified with 66 taxids
2024-11-16 04:29:55,789 - INFO - Relative abundance and genome coverage of each species can be found in result/mpg/species_stats.tsv
2024-11-16 04:29:55,789 - INFO - Writing nucleotide sequences of genes
2024-11-16 04:30:03,942 - INFO - Aligning genes to reference genomes
2024-11-16 04:30:18,339 - INFO - Obtaining IDs of reference genomes
2024-11-16 04:30:18,941 - INFO - Obtaining genes mapped to reference genomes
2024-11-16 04:30:18,942 - INFO - Obtaining amino acid sequences of genes mapped
2024-11-16 04:30:19,754 - INFO - Total number of genes: 0
2024-11-16 04:30:19,754 - INFO - Number of genes mapped: 0
1. The above is a log entry. What could be the reason for this, and what caused the output file all_genes.fna to be empty?
2. My command:
condiga \
   -c final.contigs.fa \
   -ta Kraken/kraken_result.txt \
   -g final.contigs.fa.lst \
   -cov contig_coverage.tsv \
   -as assembly_summary.txt \
   -o result/mpg
2. In the file result/mpg/species_stats.tsv, I see that the relative abundance and genome coverage for some species meet the default requirements, but the all_genes.fna file is still empty.
3. Here are the detailed error messages:
2024-11-16 04:29:55,789 - INFO - Relative abundance and genome coverage of each species can be found in result/mpg/species_stats.tsv
2024-11-16 04:29:55,789 - INFO - Writing nucleotide sequences of genes
2024-11-16 04:30:03,942 - INFO - Aligning genes to reference genomes
[M::mm_idx_gen::5.161*1.36] collected minimizers
[M::mm_idx_gen::11.921*1.00] sorted minimizers
[M::main::11.921*1.00] loaded/built the index for 133 target sequence(s)
[M::mm_mapopt_update::12.910*1.00] mid_occ = 65
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 133
[M::mm_idx_stat::13.655*0.99] distinct minimizers: 29065550 (65.39% are singletons); average occurrences: 2.086; average spacing: 5.360
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -t 8 result/mpg/Reference_Sequences/refs.fna result/mpg/all_genes.fna
[M::main] Real time: 13.761 sec; CPU: 13.635 sec; Peak RSS: 2.198 GB
2024-11-16 04:30:18,339 - INFO - Obtaining IDs of reference genomes
2024-11-16 04:30:18,941 - INFO - Obtaining genes mapped to reference genomes
2024-11-16 04:30:18,942 - INFO - Obtaining amino acid sequences of genes mapped
2024-11-16 04:30:19,754 - INFO - Total number of genes: 0
2024-11-16 04:30:19,754 - INFO - Number of genes mapped: 0
Traceback (most recent call last):
  File "/home/ghy/miniconda/miniconda3/envs/condiga/bin/condiga", line 253, in <module>
    main()
  File "/home/ghy/miniconda/miniconda3/envs/condiga/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ghy/miniconda/miniconda3/envs/condiga/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ghy/miniconda/miniconda3/envs/condiga/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ghy/miniconda/miniconda3/envs/condiga/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ghy/miniconda/miniconda3/envs/condiga/bin/condiga", line 227, in main
    logger.info(f"Percentage of genes mapped: {(len(gene_seq)-unmapped_count)/len(gene_seq)}")
ZeroDivisionError: division by zero

**Comment by edfadeev** [comment]
Hi  @gaojingxun ,
I am not sure whether we have the same issue, but I was also getting empty files.

What I have discovered is that the source of the problem was actually in the gene calling step. 
I do not know whether it is an error in the documentation here, or perhaps changes in the MetaGeneMark tool. But the command lines that should be used to get into the list file also DNA and AA sequences is:

`gmhmmp -a -d -m MetaGeneMark_v1.mod final.contigs.fa`
